services:
  minecraft:
    image: itzg/minecraft-server:latest
    container_name: minecraft-server
    restart: unless-stopped
    tty: true
    stdin_open: true
    ports:
      - "25565:25565"
    environment:
      DIFFICULTY : "easy"
      ENABLE_WHITELIST: "true"
      EULA: "true"
      MAX_PLAYERS: "10"
      MEMORY: "10G"
      SEED: "694269427171849995"
      SERVER_NAME: "MLTSF"
      TZ: "Europe/Berlin"
    volumes:
      - /home/fkoch/minecraft:/data